# Build and deploy MHA to Azure Static Web Apps

name: Build and Deploy MHA

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_VERSION: '22'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: NPM install, build
        env:
          SCM_COMMIT_ID: ${{ github.sha }}
          APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}
          MHA_NAA_CLIENT_ID: ${{ secrets.MHA_NAA_CLIENT_ID }}
        run: |
          npm ci
          npm run build --if-present

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: "Pages"
